import React from 'react';

export const AlbumIcon = '\u{1f4bf}';
export const ArtistIcon = '\u{1f464}';
export const ArtistsIcon = '\u{1f465}';
export const BlockArrowDownIcon = '\u{25bc}';
export const BlockArrowUpIcon = '\u{25b2}';
export const CloseIcon = '\u{2715}';
export const GenreIcon = '\u{1d11e}';
export const NextTrackIcon = '\u{23ed}';
export const PauseIcon = '\u{23f8}';
export const PlayIcon = '\u{25b6}';
export const PreviousTrackIcon = '\u{23ee}';
export const RepeatIcon = '\u{1f501}';
export const RepeatOnceIcon = '\u{1F502}';
export const SearchIcon = '\u{1f50e}';
export const SettingsIcon = '\u{2699}';
export const ShuffleIcon = '\u{1f500}';
export const StemmedArrowRightIcon = '\u{2192}';
export const TrashIcon = '\u{1f5d1}';
export const VolumeIcon = '\u{1f50a}';
export const YearIcon = '\u{1f4c5}';
